project:
  type: website
  output-dir: docs

website:
  title: "Dresden"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - photos.qmd
      - about.qmd
      - prices.qmd
      - location.qmd
      - contact.qmd
      - todos.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

